# Site settings
title: Kristofer Dubbels
email: me@kristofer.fail
description: Moving along.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kdubbels.github.io/" # the base hostname & protocol for your site
twitter_username: dubbelsyrfun
github_username:  kdubbels

# Build settings
markdown: kramdown

gems:
  - jemoji