# Site settings
title: Kristofer Dubbels
email: dubbk381@alumni.newschool.edu
description: Moving along. :train2:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dubbelsyrfun
github_username:  kdubbels

# Build settings
markdown: kramdown

gems:
  - jemoji