# Site settings
title: k d dot io
email: dubbk381@alumni.newschool.edu
description: Blog and portfolio about of Kristofer "the Man" Dubbels.
#baseurl: "https://kdubbels.github.io/" # the subpath of your site, e.g. /blog/
url: "http://kristoferdubbels.io/" # the base hostname & protocol for your site
twitter_username: dubbelsyrfun
github_username:  kdubbels

# Build settings
markdown: kramdown

gems:
  - jemoji